### PR TITLE
mingw-w64: build related fixes

### PR DESCRIPTION
**Pull request by 1480c1**
Some commits that I feel are generic enough that allow building with mingw-w64 with tests and examples disabled.

I didn't fix the build with tests and examples as I believe some of them are not really “fixable” on Windows and `strptime` simply does not exist on Windows and would require a lot more coding.

I can split this off into multiple PRs if this feels too much to review.

### CODE REVIEW

**Comment by ileanadumitrescu95** [comment]
Thank you for your contribution!

> Some commits that I feel are generic enough that allow building with mingw-w64 with tests and examples disabled.

I have looked over your changes, and it looks mostly good. I am hesitant to merge as is though. The tests and examples are important to have, so it would be ideal to not have the option to opt out of having them.

> I didn't fix the build with tests and examples as I believe some of them are not really “fixable” on Windows and `strptime` simply does not exist on Windows and would require a lot more coding.

Would you elaborate on what is not "fixable"?

There seem to be [alternatives](https://stackoverflow.com/questions/321849/strptime-equivalent-on-windows) made for `strptime` in Windows, but it might be better to rewrite the tests and examples to better suit cross-compilation.

**Comment by 1480c1** [comment]
> I have looked over your changes, and it looks mostly good. I am hesitant to merge as is though. The tests and examples are important to have, so it would be ideal to not have the option to opt out of having them.

The option is there mainly for people who will do automatic compilation (such as in CI when building other projects like VLC) and will never run the tests nor examples. It would help reduce the time, and thus the cost of compiling overall.

> Would you elaborate on what is not "fixable"?

For me, "fixable" is depending on a scale of how much time I have and how much time it would take to get it properly working past just commenting it out. As this was primarily focused on build fixes, I did not want to go into logic changes. At the time that I worked on this PR, although I saw the same stackoverflow page, I did not consider the effort to implement the alternatives to be within my time budget.

For `_r` functions, technically, I could just rewrite those parts to use the non suffixed version. However, I am not sure if there was a specific reason why they used the `_r` version, so I cannot be confident my changes would be correct.

As of writing this, I found [_mkgmtime](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/mkgmtime-mkgmtime32-mkgmtime64?view=msvc-170&redirectedfrom=MSDN), so I can add that to the list of changes.

In this case, the errors were
```c
make[2]: Entering directory '/d/zvbi/examples'
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -g -O2   -o pdc2.exe pdc2.o ../src/libzvbi.la  -lm  -lintl -lpthread -lm  -lws2_32 -liconv
libtool: link: gcc -g -O2 -o pdc2.exe pdc2.o  ../src/.libs/libzvbi.a -lintl -lpthread -lws2_32 -liconv
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: pdc2.o: in function `msg':
D:/zvbi/examples/pdc2.c:300:(.text+0x9b): undefined reference to `localtime_r'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: pdc2.o: in function `standby_loop':
D:/zvbi/examples/pdc2.c:1626:(.text+0x1173): undefined reference to `localtime_r'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: pdc2.o: in function `parse_test_file_line':
D:/zvbi/examples/pdc2.c:1152:(.text+0x1324): undefined reference to `strptime'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/zvbi/examples/pdc2.c:1160:(.text+0x1778): undefined reference to `timegm'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: pdc2.o: in function `parse_args':
D:/zvbi/examples/pdc2.c:1815:(.text.startup+0x113): undefined reference to `strptime'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/zvbi/examples/pdc2.c:1818:(.text.startup+0x12e): undefined reference to `strptime'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/zvbi/examples/pdc2.c:1823:(.text.startup+0x163): undefined reference to `strptime'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/zvbi/examples/pdc2.c:1828:(.text.startup+0x19e): undefined reference to `strptime'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: pdc2.o: in function `add_program_to_schedule':
D:/zvbi/examples/pdc2.c:1729:(.text.startup+0x2e0): undefined reference to `localtime_r'
collect2.exe: error: ld returned 1 exit status
```

The warnings in the compilation logs are
```c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I.. -D_REENTRANT -D_GNU_SOURCE -g -O2 -MT exp-html.lo -MD -MP -MF .deps/exp-html.Tpo -c exp-html.c -o exp-html.o
exp-html.c:203: warning: "printf" redefined
  203 | #define printf(templ, args...) \
      |
In file included from intl-priv.h:35,
                 from export.h:295,
                 from exp-html.c:36:
C:/msys64/ucrt64/include/libintl.h:398: note: this is the location of the previous definition
  398 | #  define printf libintl_printf
      |
...
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I.. -D_REENTRANT -D_GNU_SOURCE -g -O2 -MT io-bktr.lo -MD -MP -MF .deps/io-bktr.Tpo -c io-bktr.c -o io-bktr.o
In file included from bcd.h:27,
                 from lang.h:27,
                 from cache.h:30,
                 from cache-priv.h:27,
                 from teletext_decoder.h:29,
                 from vbi.h:32,
                 from io-bktr.c:29:
C:/msys64/ucrt64/include/io.h: In function '_findfirst64i32':
misc.h:436:17: warning: implicit declaration of function 'use_strlcpy_instead' [-Wimplicit-function-declaration]
  436 | #define strncpy use_strlcpy_instead
      |                 ^~~~~~~~~~~~~~~~~~~
mv -f .deps/io-bktr.Tpo .deps/io-bktr.Plo
...
gcc -DHAVE_CONFIG_H -I. -I..  -I../src   -g -O2 -MT pdc2.o -MD -MP -MF .deps/pdc2.Tpo -c -o pdc2.o pdc2.c
pdc2.c: In function 'print_time':
pdc2.c:246:9: warning: implicit declaration of function 'localtime_r'; did you mean 'localtime_s'? [-Wimplicit-function-declaration]
  246 |         localtime_r (&time, &tm);
      |         ^~~~~~~~~~~
      |         localtime_s
pdc2.c:252:9: warning: implicit declaration of function 'gmtime_r'; did you mean 'gmtime_s'? [-Wimplicit-function-declaration]
  252 |         gmtime_r (&time, &tm);
      |         ^~~~~~~~
      |         gmtime_s
pdc2.c: In function 'parse_test_file_line':
pdc2.c:1152:13: warning: implicit declaration of function 'strptime'; did you mean 'strftime'? [-Wimplicit-function-declaration]
 1152 |         s = strptime (s, "%n%Y%m%dT%H%M%S", &tm);
      |             ^~~~~~~~
      |             strftime
pdc2.c:1152:11: warning: assignment to 'const char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
 1152 |         s = strptime (s, "%n%Y%m%dT%H%M%S", &tm);
      |           ^
pdc2.c:1160:30: warning: implicit declaration of function 'timegm'; did you mean 'time'? [-Wimplicit-function-declaration]
 1160 |                 *timestamp = timegm (&tm);
      |                              ^~~~~~
      |                              time
pdc2.c: In function 'add_program_to_schedule':
pdc2.c:1729:21: warning: comparison between pointer and integer
 1729 |             || NULL == localtime_r (&pil_time, &tm)) {
      |                     ^~
pdc2.c: In function 'parse_args':
pdc2.c:1815:26: warning: comparison between pointer and integer
 1815 |                 if (NULL == strptime (argv[optind + 0], "%Y-%m-%d",
      |                          ^~
pdc2.c:1818:26: warning: comparison between pointer and integer
 1818 |                 if (NULL == strptime (argv[optind + 1], "%H:%M",
      |                          ^~
pdc2.c:1823:26: warning: comparison between pointer and integer
 1823 |                 if (NULL == strptime (argv[optind + 2], "%H:%M",
      |                          ^~
pdc2.c:1828:26: warning: comparison between pointer and integer
 1828 |                 if (NULL == strptime (argv[optind + 3], "%H:%M",
      |                          ^~
mv -f .deps/pdc2.Tpo .deps/pdc2.Po
```

**Comment by ileanadumitrescu95** [comment]
> > I have looked over your changes, and it looks mostly good. I am hesitant to merge as is though. The tests and examples are important to have, so it would be ideal to not have the option to opt out of having them.
> 
> The option is there mainly for people who will do automatic compilation (such as in CI when building other projects like VLC) and will never run the tests nor examples. It would help reduce the time, and thus the cost of compiling overall.

I understand, so I will leave in the option to opt out of having them. However, it would be better to have working tests and examples anyways. I have been working on fixing those, and they are almost all functional. I will begin pushing my changes here in the coming days.  I expect some tests/examples will be excluded until I have time to make them more robust though.

If you would do some testing with my changes, I would appreciate it. I have been using `wine` in Debian to test the Windows executables. I will attach my test file with my notes for reference.

> > Would you elaborate on what is not "fixable"?
> 
> For me, "fixable" is depending on a scale of how much time I have and how much time it would take to get it properly working past just commenting it out. As this was primarily focused on build fixes, I did not want to go into logic changes. At the time that I worked on this PR, although I saw the same stackoverflow page, I did not consider the effort to implement the alternatives to be within my time budget.
> 
> For `_r` functions, technically, I could just rewrite those parts to use the non suffixed version. However, I am not sure if there was a specific reason why they used the `_r` version, so I cannot be confident my changes would be correct.
> 
> As of writing this, I found [_mkgmtime](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/mkgmtime-mkgmtime32-mkgmtime64?view=msvc-170&redirectedfrom=MSDN), so I can add that to the list of changes.

Thank you for your hard work!

**Comment by 1480c1** [comment]
@ileanadumitrescu95 I tried running `make check` with msys2 on windows with ucrt64, I get
```bash
PASS: ctest.exe
PASS: cpptest.exe
PASS: ctest-c89.exe
PASS: ctest-gnu89.exe
PASS: ctest-c94.exe
PASS: ctest-c99.exe
PASS: ctest-gnu99.exe
PASS: cpptest-cxx98.exe
PASS: cpptest-gnuxx98.exe
PASS: test-dvb_demux.exe
../build-aux/test-driver: line 112:  2295 Segmentation fault      "$@" >> "$log_file" 2>&1
FAIL: test-dvb_mux.exe
PASS: test-hamm.exe
../build-aux/test-driver: line 112:  2305 Segmentation fault      "$@" >> "$log_file" 2>&1
FAIL: test-packet-830.exe
../build-aux/test-driver: line 112:  2310 Segmentation fault      "$@" >> "$log_file" 2>&1
FAIL: test-pdc.exe
PASS: test-raw_decoder.exe
PASS: test-vps.exe
============================================================================
Testsuite summary for zvbi 0.2.42
============================================================================
# TOTAL: 16
# PASS:  13
# SKIP:  0
# XFAIL: 0
# FAIL:  3
# XPASS: 0
# ERROR: 0
============================================================================
See test/test-suite.log
============================================================================
make[3]: *** [Makefile:1499: test-suite.log] Error 1
make[3]: Leaving directory '/d/zvbi/test'
make[2]: *** [Makefile:1607: check-TESTS] Error 2
make[2]: Leaving directory '/d/zvbi/test'
make[1]: *** [Makefile:1799: check-am] Error 2
make[1]: Leaving directory '/d/zvbi/test'
make: *** [Makefile:519: check-recursive] Error 1
```

Running gdb shows
```c
Reading symbols from ./test-dvb_mux.exe...
Starting program: D:\zvbi\test\test-dvb_mux.exe
[New Thread 29188.0x8480]
[New Thread 29188.0x7e38]
[New Thread 29188.0x8c18]

Thread 1 received signal SIGSEGV, Segmentation fault.
encode_stuffing (p=0x7e138e " ", '½' <repeats 16 times>, "■", p_left=1, last_du_size=46, fixed_length=0) at dvb_mux.c:175
175                                     p[(long) 1 - last_du_size] =
(gdb) bt
#0  encode_stuffing (p=0x7e138e " ", '½' <repeats 16 times>, "■", p_left=1, last_du_size=46, fixed_length=0) at dvb_mux.c:175
#1  0x00007ff6086ca0eb in vbi_dvb_multiplex_sliced (packet=0x5ffc88, packet_left=0x5ffc7c, sliced=0x5ffc80, sliced_left=0x5ffc78, service_mask=4294967295, data_identifier=153, stuffing=1) at dvb_mux.c:656
#2  0x00007ff6086c2d21 in assert_multiplex_sliced (p1=0x7e1360 "\002,τΣ", ' ' <repeats 43 times>, '½' <repeats 16 times>, "■", p1_size=47, s1=0x7f8c70, s1_lines=17, service_mask=4294967295, data_identifier=153, stuffing=1, exp_success=1, exp_errno=0, exp_out_lines=1,
    exp_out_data_size=47, exp_consumed_lines=1) at test-dvb_mux.cc:882
#3  0x00007ff6086c2c33 in assert_multiplex_sliced (p1=0x7e1360 "\002,τΣ", ' ' <repeats 43 times>, '½' <repeats 16 times>, "■", p1_size=47, s1=0x7f8c70, s1_lines=17, service_mask=4294967295, data_identifier=74565, stuffing=1, exp_success=1, exp_errno=0, exp_out_lines=1,
    exp_out_data_size=47, exp_consumed_lines=1) at test-dvb_mux.cc:841
#4  0x00007ff6086c418f in test_ms_packet_offset_size (offset=0, buffer_size=47, stuffing=1) at test-dvb_mux.cc:1512
#5  0x00007ff6086c41d7 in test_multiplex_sliced_packet_size () at test-dvb_mux.cc:1533
#6  0x00007ff6086c464c in test_multiplex_sliced () at test-dvb_mux.cc:1702
#7  0x00007ff6086c953b in main () at test-dvb_mux.cc:3919
-----------------------
Starting program: D:\zvbi\test\.libs\test-packet-830.exe
[New Thread 11376.0x2b1c]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ff6254c5aa5 in LibOb_strptime (source=0x7ff6254ca658 <bad_utc+824> "19820131T000000", format=0x7ff6254ca1fc <max_pil+508> "%n%Y%m%dT%H%M%S", tp=0x5ffd40, pTimeZone=0x0) at LibOb_strptime.c:1053
1053            if (*formatPosition)
(gdb) bt
#0  0x00007ff6254c5aa5 in LibOb_strptime (source=0x7ff6254ca658 <bad_utc+824> "19820131T000000", format=0x7ff6254ca1fc <max_pil+508> "%n%Y%m%dT%H%M%S", tp=0x5ffd40, pTimeZone=0x0) at LibOb_strptime.c:1053
#1  0x00007ff6254c1574 in ztime (s=0x7ff6254ca658 <bad_utc+824> "19820131T000000") at D:/zvbi/test/test-pdc.h:148
#2  0x00007ff6254c234d in main () at test-packet-830.cc:352
-----------------------
Reading symbols from .libs/test-pdc.exe...
(gdb) r
Starting program: D:\zvbi\test\.libs\test-pdc.exe
[New Thread 13988.0x899c]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ff776fb9155 in LibOb_strptime (source=0x7ff776fc281a <test_pil_from_string()::trailing_garbage+666> "20010101T000000", format=0x7ff776fc2004 <max_pil+4> "%n%Y%m%dT%H%M%S", tp=0x5ffd40, pTimeZone=0x0) at LibOb_strptime.c:1053
1053            if (*formatPosition)
(gdb) bt
#0  0x00007ff776fb9155 in LibOb_strptime (source=0x7ff776fc281a <test_pil_from_string()::trailing_garbage+666> "20010101T000000", format=0x7ff776fc2004 <max_pil+4> "%n%Y%m%dT%H%M%S", tp=0x5ffd40, pTimeZone=0x0) at LibOb_strptime.c:1053
#1  0x00007ff776fb151f in ztime (s=0x7ff776fc281a <test_pil_from_string()::trailing_garbage+666> "20010101T000000") at D:/zvbi/test/test-pdc.h:148
#2  0x00007ff776fb414e in test_pil_to_time () at test-pdc.cc:907
#3  0x00007ff776fb5071 in main () at test-pdc.cc:1141
```

Somehow, `formatPosistion` was `0x0`. Have not yet looked deep into how or why yet.

**Pull request merged**
